### ISSUE TITLE
Integration in Envpool

### ISSUE THREAD

**Issue by roger-creus** [danijar/crafter#11]
Hi!

I was wondering if there exists a plan to integrate the crafter learning environment in [Envpool](https://github.com/sail-sg/envpool).  I think it would be very useful since it would allow training agents in parallel to benefit from the high-performance framework of Envpool, and build on top of [great baselines](https://twitter.com/vwxyzjn/status/1578103417410818049?t=xkmmOU-j9QYw2r_GeN9gIg&s=31).

There exists [this guide](https://envpool.readthedocs.io/en/latest/content/new_env.html) which can be useful.

Thank you very much!

**Comment by danijar** [comment]
I won't have time for it but would be supportive if someone did.
