### ISSUE TITLE
Global View of the map

### ISSUE THREAD

**Issue by roger-creus** [danijar/crafter#12]
Hi! Is there any way to generate a global view of the map like the ones in the readme? I have seen a Global View class in engine.py but it is not implemented. Thank you!

**Comment by danijar** [comment]
There are three options, you can use the semantic full map returned in the info dict (integer coded object types, no textures), you can increase the view area a lot (it will still be centered at the agent but you can see everything at once, with bezels where needed), you can implement the global view stub you found based on the local view (it would mostly be a copy of that but I don't have time to do it).
