### ISSUE TITLE
Rainbow Hyperparameters

### ISSUE THREAD

**Issue by rfali** [danijar/crafter#14]
Hi. The paper mentions 

>  Rainbow (Hessel et al., 2018) is based on Q-Learning and combines several advances, including for exploration. The defaults for Atari did not work well, so we tuned the hyper parameters for Crafter and found a compromise between Atari defaults and the data-efficient version of the method (van Hasselt et al., 2019) to be ideal.

Are these hyperparameters available anywhere, and if not, can you please share these? The[ crafter baselines for Rainbow](https://github.com/danijar/crafter-baselines/blob/cccf96338d6e103dbb999602276e4d8e5e173433/rainbow/main.py#L26) has the same hyperparameters as Kaixhin's Rainbow (which are designed for ALE), and there are no hyper parameter values mentioned in the paper. Thanks for your time!

**Comment by danijar** [comment]
Yes, those are the hyper parameters. I tried changing a handful of them but nothing I tried ended up working as well as the defaults.
