### ISSUE TITLE
There is an functools has no "cache" error when I try to import crafter

### ISSUE THREAD

**Issue by DanielS684** [danijar/crafter#2]
The installation seems to go well but when I try to import crafter it doesn't work. I looked for some ways to solve this problem but the only solution I could find was to upgrade to Python 3.9 but I can't do that since I plan on using an online service like google colab or kaggle. What would you suggest I do?

**Comment by danijar** [comment]
Good to know, thanks for reporting this. You can just remove the cache decorator for now and it should all still work, without substantial performance difference. I will replace it with `@functools.lru_cache(1000)` in the next release so it works with older Python versions.

**Comment by DanielS684** [comment]
Thanks for the quick response but to clarify how would I remove the cache decorator?

**Comment by danijar** [comment]
There are many ways:
A) You could edit the file in your site-packages folder. The path to it should be printed in your error message.
B) You could clone the repo, edit the file, and run `pip3 install .`.
C) In your own code, before importing crafter, you could write `functools.cache = functools.lru_cache`.

**Comment by DanielS684** [comment]
Ok thank you for this project and also and the last question I have is about the module in general. When/ Are you going to implement multiagent use?

**Comment by danijar** [comment]
I made the update and the LRU cache should now work also for your Python version.

I like the idea but I don't have any plans for supporting multi-agent training in Crafter for now. Of course there are creatures other than the player in the world that it can interact with.
