### ISSUE TITLE
Running analysis scripts with jsonl files

### ISSUE THREAD

**Issue by roger-creus** [danijar/crafter#24]
Hi!

I am not being able to load the scripts in the analysis folder with the stored `.jsonl` files from the Recorder. I think the format of the saved files (line-separated dictionaries) is not the expected format for the `analysis` code. It is also not the same as the `.json` files that are stored in the `scores/` folder. Am I missing something?

Thank you!

**Comment by danijar** [comment]
Hi, I think you need to use read_metrics.py first to convert them. Does that work?
