### ISSUE TITLE
How can I render when training an agent?

### ISSUE THREAD

**Issue by LeejwUniverse** [danijar/crafter#3]
Hi, danijar.

Thanks for making a good environment.

I could check 'Play Yourself' and play the game myself. however, I just got information on (obs, reward, done, info), the gui game is not working when I tried to import crafter in a python script.  And env.render() is also not working.

could you give me the answer how can I render in a python script?

**Comment by danijar** [comment]
The `obs` itself is the 64x64x3 image of the environment. Are you trying to get a higher-resolution image for visualization?

**Comment by LeejwUniverse** [comment]
oh... sorry.. I misunderstood. I have expected to use other rendering options. Thanks for answering my question.

**Comment by danijar** [comment]
I also added the ability to render the environment in different resolutions:

```python
env = crafter.Crafter()
obs = env.reset()               # Renders in 64x64x3
image = env.render((512, 512))  # Renders in custom resolution
```

**Comment by LeejwUniverse** [comment]
Nice! I will use this. thanks!
