### ISSUE TITLE
VideoRecorder saving path error

### ISSUE THREAD

**Issue by Howuhh** [danijar/crafter#5]
First of all, thank you for this environment! 

I think VideoRecorder has a small bug that causes duplicate directories in the path, which causes an error when saving logs.

Example of an error for `directory="videos"`:
```python
FileNotFoundError: The directory '/home/project_path/videos/videos' does not exist
```
Removing `self._directory /` from filename fixes this error for me.
https://github.com/danijar/crafter/blob/e36271d45f282c991261ba18997d410c26a08bd0/crafter/recorder.py#L98

**Comment by danijar** [comment]
Thanks! Fixed.
