### ISSUE TITLE
Can't initialize the enviroment

### ISSUE THREAD

**Issue by ImaGonEs** [danijar/crafter#9]
I followed the instructions but I got the error: 

"reset() missing 1 required positional argument: 'self'"

When using:

env = crafter.Recorder(
  env, './',
  save_stats=True,
  save_video=True,
  save_episode=True,
)

env.reset()

Any solution? I really would like to try this environment :(

**Comment by danijar** [comment]
I can't reproduce this. Can you post a complete runnable example and make sure you're not using an outdated PyPi released (`pip install -U crafter`)?
